### PR TITLE
Merge my slogan

### PR DESCRIPTION
**Pull request by Miami44lb**

### CODE REVIEW

**Review by claesmk — CHANGES_REQUESTED** [review]
These changes over-write existing slogans you should add yours and not delete the others

**Comment by Miami44lb** [comment]
Im soo sorry Im just now seeing this message because its my personal email
which is drowned in other stuff... is there anyway we can have an
appointment to go through this im running this on a mac? thank you for your
time

William Parker

**Comment by claesmk** [comment]
We normally have office hours on Thursdays at 7pm.  You are very close to having this working - all you need to do is add your slogan to the end of the list without deleting the others.  If you follow the instructions in the slides from the sprint-2 [instructions](https://github.com/orgs/NCATComp410/teams/comp410summer2021class/discussions/3) it should work.  The Mac is only slightly different, you'd use terminal instead of opening powershell.

**Review by claesmk — APPROVED** [review]
Looks good

**Pull request merged**
